name: Scaffold new service repository from Cookiecutter

on:
  workflow_dispatch:
    inputs:
      port_payload:
        required: true
        description: "Port's payload, including details for who triggered the action and general context (blueprint, run id, etc...)"
        type: string
    secrets:
      ORG_TOKEN:
        required: true
      WEBINAR_CLIENT_ID:
        required: true
      WEBINAR_CLIENT_SECRET:
        required: true
jobs:
  scaffold:
    runs-on: ubuntu-latest
    steps:
      - name: Add log to Port action
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.WEBINAR_CLIENT_ID }}
          clientSecret: ${{ secrets.WEBINAR_CLIENT_SECRET }}
          operation: PATCH_RUN
          runId: ${{ fromJson(inputs.port_payload).context.runId }}
          logMessage: "Scaffolding a new repository from Cookiecutter template 🏃‍♂️"
      - uses: port-labs/cookiecutter-gha@v1
        with:
          portClientId: ${{ secrets.WEBINAR_CLIENT_ID }}
          portClientSecret: ${{ secrets.WEBINAR_CLIENT_SECRET }}
          token: ${{ secrets.ORG_TOKEN }}
          portRunId: ${{ fromJson(inputs.port_payload).context.runId }}
          repositoryName: ${{ fromJson(inputs.port_payload).payload.properties.name }}
          portUserInputs: ${{ toJson(fromJson(inputs.port_payload).payload.properties.options) }}
          cookiecutterTemplate: ${{ fromJson(inputs.port_payload).payload.properties.template }}
          blueprintIdentifier: "microservice"
          organizationName: port-live-webinar
